version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: certificadosapp_sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Certificados!@12345"
    ports:
      - "1435:1433"
    volumes:
      - sqlserver-data-certificadosapp:/var/opt/mssql
    restart: unless-stopped
    networks:
      - certificadosapp_network

networks:
  certificadosapp_network:
    driver: bridge

volumes:
  sqlserver-data-certificadosapp: